media:
  input: images
  output: /images

content:
  - name: projets
    label: Projets
    type: collection
    path: projets
    fields:
      - name: projet
        label: Titre
        type: string
      - name: description
        label: Description
        type: string
      - name: année
        label: Année
        type: string
      - name: pratique
        label: pratique
        type: string
        list: true
      - name: lieu
        label: Lieu
        type: string
      - name: auteurs
        label: Auteurs
        type: string
      - name: documents
        label: Documents
        type: object
        list: true
        fields:
          - name: document
            label: Type de document
            type: string
            list: true
          - name: date
            label: Date
            type: string
          - name: description
            label: Description
            type: string
          - name: lieu
            label: Lieu
            type: string
          - name: photos
            label: Photos
            type: image
            list: true

  - name: references
    label: Références
    type: collection
    path: references
    fields:
      - name: titre
        label: Titre
        type: string
      - name: type
        label: Type
        type: string
      - name: auteur
        label: Auteur
        type: string
      - name: année
        label: Année
        type: string
      - name: description
        label: Description
        type: string
      - name: photos
        label: Images
        type: image
        list: true
      - name: url
        label: Lien
        type: string

  - name: ressources
    label: Ressources
    type: collection
    path: ressources
    fields:
      - name: titre
        label: Titre
        type: string
      - name: url
        label: URL
        type: string
      - name: categorie
        label: Catégorie
        type: string
      - name: description
        label: Description
        type: string