media:
  - name: images
    label: Images
    input: images
    output: images
 
content:
  - name: projets
    label: Projets
    type: collection
    path: projets
    view:
      fields: [projet, année, lieu]
    fields:
      - name: projet
        label: Titre du projet
        type: string
      - name: description
        label: Description
        type: string
      - name: année
        label: Année
        type: string
      - name: type
        label: Type
        type: string
        list: true
      - name: lieu
        label: Lieu
        type: string
      - name: auteurs
        label: Auteurs
        type: string
      - name: soustype
        label: Type de document
        type: string
        options:
          - Photos
          - Dessins
          - Plans
          - Rendus
          - Texte
          - Scans
      - name: photos
        label: Photos
        type: image
        list: true
 
  - name: references
    label: Références
    type: collection
    path: references
    view:
      fields: [titre, type, année]
    fields:
      - name: titre
        label: Titre
        type: string
      - name: type
        label: Type
        type: string
        options:
          - Livre
          - Film
          - Gravure
          - Photographie
          - Dessin
          - Autre
      - name: auteur
        label: Auteur
        type: string
      - name: année
        label: Année
        type: string
      - name: description
        label: Description
        type: string
      - name: photos
        label: Images
        type: image
        list: true
      - name: url
        label: Lien
        type: string
 
  - name: ressources
    label: Ressources
    type: collection
    path: ressources
    view:
      fields: [titre, categorie]
    fields:
      - name: titre
        label: Titre
        type: string
      - name: url
        label: URL
        type: string
      - name: categorie
        label: Catégorie
        type: string
        options:
          - Outil
          - Site
          - Archive
          - Autre
      - name: description
        label: Description
        type: string
 
  - name: about
    label: À propos
    type: file
    file: about/index.md
    fields:
      - name: titre
        label: Titre
        type: string
      - name: body
        label: Contenu
        type: rich-text